CREATE database IF NOT EXISTS PillReminderApp;
USE `PillReminderApp`;
 
CREATE TABLE IF NOT EXISTS UserInfo (
UserId INT AUTO_INCREMENT PRIMARY KEY,
UserName VARCHAR(60) NOT NULL,
UserEmailAddress VARCHAR(60) NOT NULL UNIQUE,
UserContactNumber BIGINT DEFAULT NULL,
UserCountry VARCHAR(60) DEFAULT NULL,
UserDoB DATE NULL DEFAULT NULL,
UserPassword VARCHAR(60) NOT NULL
);